### ISSUE TITLE
First

### ISSUE THREAD

**Issue by TofPlays** [CalebGitBritannia/ToffyDungeons#3]
Obligatory "First"

**Comment by JamesThack** [comment]
Thank you for your feedback Mr Tof, however to review your issue I must ask that you follow the standard git issue format which is as follows:

==
1.) How to replicate the issue?
2.) Possible conflicts (other plugins)
3.) Version (both plugin and minecraft)
==

Thank you however for your time, I will be closing the issue but please feel free to create a new one with more information! 
(Also ily Tof <3)
